Repository jupyterlab/jupyterlab-probot, pull requests merged in 2021-09, with the labels that each got.

#1 Add Binder Link Comment Handler
  README.md
  package-lock.json
  package.json
  src/index.ts
  test/fixtures/pull_request.opened.json
  test/index.test.ts
Labels: enhancement

#2 Add JSON Schema Validation
  package-lock.json
  package.json
  schema.json
  src/index.ts
Labels: enhancement

#3 Update README.md
  README.md
Labels: documentation

#4 Improve binder link handling
  src/index.ts
  test/index.test.ts
Labels: maintenance

#5 Don't run CI twice on PRs
  .github/workflows/test.yml
Labels: maintenance
